// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// particleFilter
List particleFilter(Rcpp::NumericVector p, double pinit, Rcpp::NumericVector m, Rcpp::NumericVector params, int n_particles, double initialState);
RcppExport SEXP _ExtChiarella_particleFilter(SEXP pSEXP, SEXP pinitSEXP, SEXP mSEXP, SEXP paramsSEXP, SEXP n_particlesSEXP, SEXP initialStateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type pinit(pinitSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type n_particles(n_particlesSEXP);
    Rcpp::traits::input_parameter< double >::type initialState(initialStateSEXP);
    rcpp_result_gen = Rcpp::wrap(particleFilter(p, pinit, m, params, n_particles, initialState));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ExtChiarella_particleFilter", (DL_FUNC) &_ExtChiarella_particleFilter, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_ExtChiarella(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
