# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

particleFilterCpp <- function(p, pinit, m, params, n_particles, initialState) {
    .Call(`_ExtChiarella_particleFilter`, p, pinit, m, params, n_particles, initialState)
}

